contentDir: '../docs'
title: 'Isotope eCommerce Documentation'
theme: 'hugo-theme-relearn'
canonifyURLs: true
enableGitInfo: true
disablePathToLower: true
outputs:
  home: [html, rss]
markup:
  goldmark:
    parser:
      autoHeadingIDType: blackfriday
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
  highlight:
    noClasses: false
